# Generated by Django 3.0.6 on 2020-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='important',
        ),
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
