# Generated by Django 3.0.6 on 2020-05-31 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0003_auto_20200531_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
