# Generated by Django 3.0.6 on 2020-06-04 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0008_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
