# Generated by Django 3.0.6 on 2020-06-07 13:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0009_meal_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='fooddiary/images/'),
            preserve_default=False,
        ),
    ]
