# Generated by Django 3.0.6 on 2020-06-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0011_remove_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(default='fooddiay/images/MyPhoto.jpg', upload_to='fooddiary/images/'),
        ),
    ]
