# Generated by Django 3.0.6 on 2020-06-07 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0013_remove_meal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
