# Generated by Django 3.0.6 on 2020-06-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0016_activity_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='fooddiary/images'),
        ),
    ]
