# Generated by Django 3.0.6 on 2020-06-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fooddiary', '0018_auto_20200608_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='image',
        ),
    ]
